# public/admin/config.yml
backend:
  name: git-gateway # For Netlify integration
  branch: main # Or your default branch (e.g., master)

# Local backend is used during development (npm run dev)
# Comment out or remove before deploying to Netlify
# local_backend: true

media_folder: "public/images/uploads" # Where media files are stored relative to root
public_folder: "/images/uploads" # The src attribute for the media file in the frontend

# Optional: Enable Editorial Workflow
publish_mode: editorial_workflow

collections:
  - name: "pages" # Example: Managing individual pages
    label: "Pages"
    folder: "src/content/pages" # Store content files here (e.g., src/content/pages/home.md)
    create: true # Allow creating new pages
    slug: "{{slug}}" # Filename based on title or manual input
    fields: # Define the content structure for pages
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      # Add fields for hero sections, features, testimonials etc.

  - name: "settings" # Example: Managing global site settings
    label: "Site Settings"
    files: # Use 'files' for single configuration items
      - file: "src/content/settings/general.json" # Store settings data here
        label: "General Settings"
        name: "general"
        fields:
          - { label: "Site Name", name: "site_name", widget: "string" }
          - { label: "Contact Email", name: "contact_email", widget: "string", required: false }
          # Add fields for logo, social links, etc. 